config/routes.rb
Cars::Application.routes.draw do

  get "sessions/new"
  resources :users

  resources :cars do
    resources :bids
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  get '/signup',  :to => 'users#new'
  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  
  root 'sessions#new'
  
  

  

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :car


  validate :check_if_highest_bid

  after_save :update_car
  after_destroy :update_car

  def update_car
    self.car.check_highest_bid
  end

  def check_if_highest_bid
    errors.add(:amount, "must be higher than current bid") unless self.car.startprize < self.amount
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create

    @car = Car.find(params[:car_id])
      @bid = @car.bids.create(params[:bid].permit(:bidder, :amount))
      redirect_to car_path(@car)
      #@bid = Bid.new(bid_params)





  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:bidder, :amount, :car_id)
    end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bid.html.erb
<p>
  <strong>Bidder:</strong>
  <%= bid.bidder %>
</p>

<p>
  <strong>Amount:</strong>
  <%= bid.amount %>
</p>

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bidder %><br>
    <%= f.text_field :bidder %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :car %><br>
    <%= f.text_field :car %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h2>Editing bid</h2>

<% if session[:current_user_id] == nil %>
<%= render 'layouts/error' %>
<% else %>
<%= render 'form' %>
<% end %>	

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<h1>Listing bids</h1>

<table>
  <thead>
    <tr>
      <th>Bidder</th>
      <th>Amount</th>
      <th>Car</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.bidder %></td>
        <td><%= bid.amount %></td>
        <td><%= bid.car %></td>
        <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h2>New bid</h2>

<% if session[:current_user_id] == nil %>
<%= render 'layouts/error' %>
<% else %>
<%= render 'form' %>
<% end %>	

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>


<% if session[:current_user_id] == nil %>
<%= render 'layouts/error' %>
<% else %>


<p>
  <strong>Bidder:</strong>
  <%= @bid.bidder %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bid.amount %>
</p>

<p>
  <strong>Car:</strong>
  <%= @bid.car %>
</p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |

<% end %>	

<%= link_to 'Back', bids_path %>