config/routes.rb
Cars::Application.routes.draw do

  get "sessions/new"
  resources :users

  resources :cars do
    resources :bids
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  get '/signup',  :to => 'users#new'
  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  
  root 'sessions#new'
  
  

  

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :bids

  validates :title, presence: true, length: { minimum: 5 }
  validates :brand, length: { minimum: 2 }
  validates :model, length: { minimum: 2 }
  validates :color, length: { minimum: 2 }
  validates :startprize, numericality: true


  def check_highest_bid
    highest_bid = self.bids.order("amount DESC").first.amount rescue 0
    self.startprize = highest_bid
    save
  end



end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:title, :brand, :model, :mileage, :color, :startprize, :duration, :description, :creator)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/#_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :mileage %><br>
    <%= f.number_field :mileage %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :startprize %><br>
    <%= f.number_field :startprize %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.datetime_select :duration %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :mileage %>
    <%= f.number_field :mileage %>
  </div>
  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :startprize %>
    <%= f.number_field :startprize %>
  </div>
  <div class="field">
    <%= f.label :duration %>
    <%= f.datetime_select :duration,{ :order => [:day, :month, :year, :hour,:minute], :start_year => Time.now.year }, {:class => 'date-select'}%>  </div>
  

  
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  
  <%= f.hidden_field :creator, :value => session[:current_user_id] %>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h2>Editing car</h2>
<hr />

<% if session[:current_user_id] == nil %>
<%= render 'layouts/error' %>
<% else %>
<%= render 'form' %>
<% end %>	
<hr />
<h2>
<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>
</h2>

app/views/cars/index.html.erb
<h2>Listing cars</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Brand</th>
      <th>Current Bid</th>
      <th>Duration</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>


      <tr>
        <td><%= car.title %></td>
        <td><%= car.brand %></td>
        <td><%= car.startprize %></td>
        <% if DateTime.now > car.duration %>
            <td>expired</td>
        <% else %>

        <td><%= car.duration %></td>
        <% end %>
		
<% if session[:current_user_id] == car.creator %>
 <td class="show"><%= link_to 'Show', car %></td>
 <td><%= link_to 'Edit', edit_car_path(car) %></td>
 <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% else %>
 <td class="show"><%= link_to 'Show', car %></td>
 <td>-</td>
 <td>-</td>
<% end %>		
		
		
		
		
      </tr>
    <% end %>
  </tbody>
</table>

<h2><%= link_to "Add a new car", new_car_path %><h2>

app/views/cars/new.html.erb
<h2>New car</h2>


<% if session[:current_user_id] == nil %>
<%= render 'layouts/error' %>
<% else %>
<%= render 'form' %>
<% end %>		

app/views/cars/show.html.erb
<h2>
<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>
</h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @car.title %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @car.mileage %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Current Bid:</strong>
  <%= @car.startprize %>
</p>

<p>
  <strong>Duration:</strong>
  <% if DateTime.now > @car.duration %>
    expired
<% else %>
    <%= @car.duration %>
<% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @car.description %>
</p>

<hr />

<h2>current bid:</h2>

<% if @car.bids.blank? %>
    <p>No bid yet</p>
<% else %>
    <%= render @car.bids.last %>
<% end %>

<% if DateTime.now > @car.duration %>
    <h2>Auction expired</h2>
<% else %>

<% if session[:current_user_id] == nil %>
<%= render 'layouts/error' %>
<% else %>
		


    <h2>Add a bid:</h2>
    <%= form_for([@car, @car.bids.build]) do |f| %>
        <p>
          <%= f.label :bidder %><br />
          <%= f.text_field :bidder %>
        </p>
        <p>
          <%= f.label :amount %><br />
          <%= f.text_field :amount %>
        </p>
        <p>
          <%= f.submit %>
        </p>
    <% end %>
	
<% end %>	
	
<% end %>